# This is an example goreleaser.yaml file with some sensible defaults.
# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "386"
      - "arm64"
    ldflags: -s -w -X github.com/get-woke/woke/cmd.Version={{.Version}} -X github.com/get-woke/woke/cmd.Commit={{.ShortCommit}} -X github.com/get-woke/woke/cmd.Date={{.Date}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^dev:'
    - 'README'
    - '^chore(deps):'
    - '^ci:'
    - Merge pull request
    - Merge branch

dockers:
  - dockerfile: build/Dockerfile
    image_templates:
      - "getwoke/woke:latest"
      - "getwoke/woke:{{ .Major }}.{{ .Minor }}"
      - "getwoke/woke:{{ .RawVersion }}"

brews:
  - tap:
      owner: get-woke
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://getwoke.tech
    description: Detect non-inclusive language in your source code.
    test: |
      system "#{bin}/woke --version"

scoop:
  bucket:
    owner: get-woke
    name: scoop-bucket
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

  # The project name and current git tag are used in the format string.
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

  homepage: https://getwoke.tech
  description: Detect non-inclusive language in your source code.
  license: MIT

  # Persist data between application updates
  # persist:
  # - "data"
  # - "config.toml"
