- id: woke
  name: 'woke'
  entry: scripts/pre-commit.sh
  language: 'script'
  description: "Runs `woke`"
- id: woke-from-source
  name: 'woke'
  entry: woke
  args: [--exit-1-on-failure]
  # The 'go' binary on your path must be at least version 1.18.
  language: 'golang'
  description: "Runs `woke`, building it from source on demand"
