// Code generated by internal/rule/gen.go; DO NOT EDIT.
// Regenerate with 'go generate ./...'

package rule

// BlacklistRule is the default rule for "blacklist"
var BlacklistRule = Rule{
	Name:         "blacklist",
	Terms:        []string{"blacklist", "black-list", "blacklisted", "black-listed"},
	Alternatives: []string{"denylist", "blocklist"},
	Severity:     1,
}

// DummyRule is the default rule for "dummy"
var DummyRule = Rule{
	Name:         "dummy",
	Terms:        []string{"dummy"},
	Alternatives: []string{"placeholder", "sample"},
}

// GrandfatheredRule is the default rule for "grandfathered"
var GrandfatheredRule = Rule{
	Name:         "grandfathered",
	Terms:        []string{"grandfathered"},
	Alternatives: []string{"legacy status"},
}

// GuysRule is the default rule for "guys"
var GuysRule = Rule{
	Name:         "guys",
	Terms:        []string{"guys"},
	Alternatives: []string{"folks", "people", "you all", "y'all"},
}

// HeRule is the default rule for "he"
var HeRule = Rule{
	Name:         "he",
	Terms:        []string{"he", "his", "him"},
	Alternatives: []string{"they", "them", "their"},
}

// ManHoursRule is the default rule for "man-hours"
var ManHoursRule = Rule{
	Name:         "man-hours",
	Terms:        []string{"man hours", "man-hours"},
	Alternatives: []string{"person hours", "engineer hours"},
}

// MasterSlaveRule is the default rule for "master-slave"
var MasterSlaveRule = Rule{
	Name:         "master-slave",
	Terms:        []string{"master-slave", "master/slave"},
	Alternatives: []string{"leader/follower", "primary/replica", "primary/standby"},
}

// SanityRule is the default rule for "sanity"
var SanityRule = Rule{
	Name:         "sanity",
	Terms:        []string{"sanity"},
	Alternatives: []string{"confidence", "quick check", "coherence check"},
}

// SlaveRule is the default rule for "slave"
var SlaveRule = Rule{
	Name:         "slave",
	Terms:        []string{"slave"},
	Alternatives: []string{"follower", "replica", "standby"},
}

// WhitelistRule is the default rule for "whitelist"
var WhitelistRule = Rule{
	Name:         "whitelist",
	Terms:        []string{"whitelist", "white-list", "whitelisted", "white-listed"},
	Alternatives: []string{"allowlist"},
	Severity:     1,
}

// DefaultRules are the default rules always used
var DefaultRules = []*Rule{
	&BlacklistRule,
	&DummyRule,
	&GrandfatheredRule,
	&GuysRule,
	&HeRule,
	&ManHoursRule,
	&MasterSlaveRule,
	&SanityRule,
	&SlaveRule,
	&WhitelistRule,
}
