// Code generated by internal/rule/gen.go; DO NOT EDIT.
// Regenerate with 'go generate ./...'

package rule

// WhitelistRule is the default rule for "whitelist"
var WhitelistRule = Rule{
	Name:         "whitelist",
	Terms:        []string{"whitelist", "white-list"},
	Alternatives: []string{"allowlist"},
	Severity:     1,
}

// BlacklistRule is the default rule for "blacklist"
var BlacklistRule = Rule{
	Name:         "blacklist",
	Terms:        []string{"blacklist", "black-list"},
	Alternatives: []string{"denylist", "blocklist"},
	Severity:     1,
}

// DefaultRules are the default rules always used
var DefaultRules = []*Rule{
	&WhitelistRule,
	&BlacklistRule,
}
